package com.verdenroz.verdaxmarket.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val positiveTextColor = Color(0xFF26A87F)
val positiveBackgroundColor = Color(0xFFA2EBD3)
val negativeTextColor = Color(0xFFDF4661)
val negativeBackgroundColor = Color(0x55DF4661)

val primaryLight = Color(0xBF123636)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xCD354B4E)
val onPrimaryContainerLight = Color(0xFFAFD8DF)
val secondaryLight = Color(0xFF013A38)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF164645)
val onSecondaryContainerLight = Color(0xFFADDDDB)
val tertiaryLight = Color(0xFF00181B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF409288)
val onTertiaryContainerLight = Color(0xFFA4CAD0)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF9FB)
val onBackgroundLight = Color(0xFF1B1C1D)
val surfaceLight = Color(0xFFFAF9FB)
val onSurfaceLight = Color(0xFF1B1C1D)
val surfaceVariantLight = Color(0xFFDFE3E9)
val onSurfaceVariantLight = Color(0xFF43474C)
val outlineLight = Color(0xFF73777D)
val outlineVariantLight = Color(0xFFC3C7CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303032)
val inverseOnSurfaceLight = Color(0xFFF2F0F2)
val inversePrimaryLight = Color(0xFFB2C9E2)
val surfaceDimLight = Color(0xFFDBD9DB)
val surfaceBrightLight = Color(0xFFFAF9FB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F3F5)
val surfaceContainerLight = Color(0xFFEFEDEF)
val surfaceContainerHighLight = Color(0xFFE9E8E9)
val surfaceContainerHighestLight = Color(0xFFE3E2E4)

val primaryDark = Color(0xFF010407)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF394D50)
val onPrimaryContainerDark = Color(0xFFDBE2EB)
val secondaryDark = Color(0xFFA0CFCD)
val onSecondaryDark = Color(0xFF011F1E)
val secondaryContainerDark = Color(0xFF002D2D)
val onSecondaryContainerDark = Color(0xFF8DBCBA)
val tertiaryDark = Color(0xFF92C9BC)
val onTertiaryDark = Color(0xFF0D353B)
val tertiaryContainerDark = Color(0xFF295249)
val onTertiaryContainerDark = Color(0xFF8AB0B6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121315)
val onBackgroundDark = Color(0xFFE3E2E4)
val surfaceDark = Color(0xFF121315)
val onSurfaceDark = Color(0xFFE3E2E4)
val surfaceVariantDark = Color(0xFF43474C)
val onSurfaceVariantDark = Color(0xFFC3C7CD)
val outlineDark = Color(0xFF8D9197)
val outlineVariantDark = Color(0xFF43474C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E4)
val inverseOnSurfaceDark = Color(0xFF303032)
val inversePrimaryDark = Color(0xFF4B6076)
val surfaceDimDark = Color(0xFF121315)
val surfaceBrightDark = Color(0xFF38393B)
val surfaceContainerLowestDark = Color(0xFF0D0E10)
val surfaceContainerLowDark = Color(0xFF1B1C1D)
val surfaceContainerDark = Color(0xFF1F2021)
val surfaceContainerHighDark = Color(0xFF292A2C)
val surfaceContainerHighestDark = Color(0xFF343536)






